[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm install'
]

[phases.build]
cmds = [
    'npm run production',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'