services:
  - type: web
    name: salwa-ecommerce
    runtime: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run production
      cp .env.example .env
      echo "APP_KEY=base64:$(openssl rand -base64 32)" >> .env
      touch database/database.sqlite
    startCommand: |
      php artisan migrate --force
      php artisan db:seed --force
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: "متجر سلوى الإلكتروني"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite